Adding A new Component
Shivamraghu1208/aem-training pull request #1
Opened 2024-05-17 12:34 UTC by Shivamraghu1208

2024-05-17 13:59 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java
> +    MoviesService moviesService;
No use of this moviesService variable, please remove this.

2024-05-17 14:10 UTC, akashsen-aurx requested changes

2024-05-17 14:10 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/services/impl/ProductDetailServiceImpl.java
> +        String s = configuration.apiUrl();
Variable name should be meaning full.

2024-05-17 14:10 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/services/impl/MoviesServiceImpl.java
> +    String[] str;
Variable name should be meaningfull

2024-05-17 14:10 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/productdetail/_cq_dialog/.content.xml
> +                            name="./select">
Give more meaning full name

2024-05-17 14:10 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/productdetail/_cq_dialog/.content.xml
> +                                    text="h6 tag"
update this property

2024-05-17 14:10 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/productdetail/_cq_dialog/.content.xml
> +                            name="./NumOfProducts"
Provide meaning full Name

2024-05-17 14:10 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/structure/StudentPage/customfooterlibs.html
> +    <sly data-sly-call="${clientlib.js @ categories='employee-clientlib'}"/>
What is the need of this clientlibs in page

2024-05-17 14:10 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java
> +        return movies;
Are you using this getter anywhere, if not then remove

2024-05-17 14:10 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java
> +    ArrayList<Product> list = new ArrayList<>();
Update variable name

2024-05-17 14:10 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java
> +                        Product p = new Product();
Where is the Product class in project

2024-05-20 06:05 UTC, abhinav-agarwal requested changes

2024-05-20 06:05 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java
> +    MoviesService moviesService;
pls mark this as private.

2024-05-20 06:05 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java
> +    ProductDetailService productDetailService;
pls mark this as private

2024-05-20 06:05 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java
> +    String heading;
pls mark this as private

2024-05-20 06:05 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java
> +    public String[] getMovies() {
move this method after below the variables declaration.

2024-05-20 06:05 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java
> +    String response;
pls mark this as private

2024-05-20 06:05 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java
> +    ArrayList<Product> list = new ArrayList<>();
pls mark this as private

2024-05-20 06:05 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java
> +    String select;
pls mark this as private

2024-05-20 06:05 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java
> +    long NumOfProducts;
pls mark this as private

2024-05-20 06:05 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java
> +            if (!jsonObject.get("products").isJsonNull()) {
merge if statements on line number 72 & 73

2024-05-20 06:05 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/services/impl/MoviesServiceImpl.java
> +    String[] str;
mark this as private

2024-05-20 06:05 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/services/impl/ProductDetailServiceImpl.java
> +            e.printStackTrace();
why printstacktrace, add a logger

2024-05-20 06:36 UTC, Shivamraghu1208 commented
Hello sir,

Requested changes updated.

________________________________
From: abhinav-agarwal ***@***.***>
Sent: 20 May 2024 11:35
To: Shivamraghu1208/aem-training ***@***.***>
Cc: Shivam Raghuwanshi ***@***.***>; Author ***@***.***>
Subject: Re: [Shivamraghu1208/aem-training] Adding A new Component (PR #1)


@abhinav-agarwal requested changes on this pull request.

________________________________

In core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java<https://github.com/Shivamraghu1208/aem-training/pull/1#discussion_r1605045140>:

> +import org.apache.sling.api.resource.Resource;
+import org.apache.sling.models.annotations.DefaultInjectionStrategy;
+import org.apache.sling.models.annotations.Model;
+import org.apache.sling.models.annotations.injectorspecific.OSGiService;
+import org.apache.sling.models.annotations.injectorspecific.ValueMapValue;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+import javax.annotation.PostConstruct;
+import java.util.ArrayList;
+
***@***.***(adaptables = Resource.class, defaultInjectionStrategy = DefaultInjectionStrategy.OPTIONAL)
+public class ProductDetailModel {
+
+    @OSGiService
+    MoviesService moviesService;


pls mark this as private.

________________________________

In core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java<https://github.com/Shivamraghu1208/aem-training/pull/1#discussion_r1605045263>:

> +import org.apache.sling.models.annotations.Model;
+import org.apache.sling.models.annotations.injectorspecific.OSGiService;
+import org.apache.sling.models.annotations.injectorspecific.ValueMapValue;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+import javax.annotation.PostConstruct;
+import java.util.ArrayList;
+
***@***.***(adaptables = Resource.class, defaultInjectionStrategy = DefaultInjectionStrategy.OPTIONAL)
+public class ProductDetailModel {
+
+    @OSGiService
+    MoviesService moviesService;
+    @OSGiService
+    ProductDetailService productDetailService;


pls mark this as private

________________________________

In core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java<https://github.com/Shivamraghu1208/aem-training/pull/1#discussion_r1605045378>:

> +import org.apache.sling.models.annotations.injectorspecific.ValueMapValue;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+import javax.annotation.PostConstruct;
+import java.util.ArrayList;
+
***@***.***(adaptables = Resource.class, defaultInjectionStrategy = DefaultInjectionStrategy.OPTIONAL)
+public class ProductDetailModel {
+
+    @OSGiService
+    MoviesService moviesService;
+    @OSGiService
+    ProductDetailService productDetailService;
+    @ValueMapValue
+    String heading;


pls mark this as private

________________________________

In core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java<https://github.com/Shivamraghu1208/aem-training/pull/1#discussion_r1605046540>:

> +import javax.annotation.PostConstruct;
+import java.util.ArrayList;
+
***@***.***(adaptables = Resource.class, defaultInjectionStrategy = DefaultInjectionStrategy.OPTIONAL)
+public class ProductDetailModel {
+
+    @OSGiService
+    MoviesService moviesService;
+    @OSGiService
+    ProductDetailService productDetailService;
+    @ValueMapValue
+    String heading;
+
+    private Logger logger = LoggerFactory.getLogger(ProductDetailModel.class);
+
+    public String[] getMovies() {


move this method after below the variables declaration.

________________________________

In core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java<https://github.com/Shivamraghu1208/aem-training/pull/1#discussion_r1605046663>:

> +    @OSGiService
+    MoviesService moviesService;
+    @OSGiService
+    ProductDetailService productDetailService;
+    @ValueMapValue
+    String heading;
+
+    private Logger logger = LoggerFactory.getLogger(ProductDetailModel.class);
+
+    public String[] getMovies() {
+        return movies;
+    }
+
+    private String[] movies;
+
+    String response;


pls mark this as private

________________________________

In core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java<https://github.com/Shivamraghu1208/aem-training/pull/1#discussion_r1605046795>:

> +
+    private Logger logger = LoggerFactory.getLogger(ProductDetailModel.class);
+
+    public String[] getMovies() {
+        return movies;
+    }
+
+    private String[] movies;
+
+    String response;
+
+    public ArrayList<Product> getList() {
+        return list;
+    }
+
+    ArrayList<Product> list = new ArrayList<>();


pls mark this as private

________________________________

In core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java<https://github.com/Shivamraghu1208/aem-training/pull/1#discussion_r1605046942>:

> +
+    String response;
+
+    public ArrayList<Product> getList() {
+        return list;
+    }
+
+    ArrayList<Product> list = new ArrayList<>();
+
+    public String getResponse() {
+        return response;
+    }
+
+
+    @ValueMapValue
+    String select;


pls mark this as private

________________________________

In core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java<https://github.com/Shivamraghu1208/aem-training/pull/1#discussion_r1605047055>:

> +    public ArrayList<Product> getList() {
+        return list;
+    }
+
+    ArrayList<Product> list = new ArrayList<>();
+
+    public String getResponse() {
+        return response;
+    }
+
+
+    @ValueMapValue
+    String select;
+
+    @ValueMapValue
+    long NumOfProducts;


pls mark this as private

________________________________

In core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java<https://github.com/Shivamraghu1208/aem-training/pull/1#discussion_r1605048105>:

> +    public String getHeading() {
+        return heading;
+    }
+
+    public String getSelect() {
+        return select;
+    }
+
+
+    @PostConstruct
+    protected void init() {
+
+        response = productDetailService.getResponse();
+        JsonObject jsonObject = JsonParser.parseString(response).getAsJsonObject();
+        if (!jsonObject.isJsonNull()) {
+            if (!jsonObject.get("products").isJsonNull()) {


merge if statements on line number 72 & 73

________________________________

In core/src/main/java/com/adobe/aem/sample/site/core/services/impl/MoviesServiceImpl.java<https://github.com/Shivamraghu1208/aem-training/pull/1#discussion_r1606290128>:

> @@ -0,0 +1,26 @@
+package com.adobe.aem.sample.site.core.services.impl;
+
+import com.adobe.aem.sample.site.core.services.MoviesService;
+import com.adobe.aem.sample.site.core.services.config.MoviesServiceConfiguration;
+import org.osgi.service.component.annotations.Activate;
+import org.osgi.service.component.annotations.Component;
+import org.osgi.service.component.annotations.Modified;
+import org.osgi.service.metatype.annotations.Designate;
+
***@***.***(service = MoviesService.class, immediate = false)
***@***.***(ocd= MoviesServiceConfiguration.class)
+public class MoviesServiceImpl implements MoviesService {
+
+    String[] str;


mark this as private

________________________________

In core/src/main/java/com/adobe/aem/sample/site/core/services/impl/ProductDetailServiceImpl.java<https://github.com/Shivamraghu1208/aem-training/pull/1#discussion_r1606290592>:

> +
+    @Activate
+    @Modified
+    protected void activate(ProductDetailServiceConfiguration configuration){
+        String apiUrl = configuration.apiUrl();
+
+        try {
+          URL url = new URL(apiUrl);
+            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
+            connection.setRequestProperty("accept", "application/json");
+            InputStream inputStream = connection.getInputStream();
+            response = IOUtils.toString(inputStream, StandardCharsets.UTF_8);
+  [...]

2024-05-23 07:08 UTC, abhinav-agarwal requested changes

2024-05-23 07:08 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/services/config/ProductDetailServiceConfiguration.java
> +    String apiUrl();
this should be api_url

2024-05-23 07:08 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java
> +    ArrayList<Product> list = new ArrayList<>();
still not private

2024-05-23 07:08 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/models/ProductDetailModel.java
> +                        Product p = new Product();
please use a meaningful variable name

2024-05-23 13:07 UTC, abhinav-agarwal approved these changes

2024-05-23 13:08 UTC, merged