Adding Js and Css files
Shivamraghu1208/aem-training pull request #3
Opened 2024-05-30 06:51 UTC by Shivamraghu1208

2024-05-30 07:16 UTC, abhinav-agarwal commented
Please put a correct PR title

2024-05-30 07:25 UTC, akashsen-aurx requested changes

2024-05-30 07:25 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/componentreport/componentreport.html
> +<button class="button" id="button">${report.buttonLabel}</button>
Id should not provide in component

2024-05-30 07:25 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/componentreport/componentreport.html
> + <div id="response-container"></div>
Id should not provide

2024-05-30 07:25 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/structure/StudentPage/customfooterlibs.html
> +    <sly data-sly-call="${clientlib.all @ categories='ClientReportLibs'}"/>
Call js in footerlibs and css in headerlibs

2024-05-30 07:25 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/structure/StudentPage/customheaderlibs.html
> +    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
Do we have any other way to include jquery, because in this case every time of page load a request call will go.

2024-05-30 07:25 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/componentreport/componentreport.html
> +<select class="select" id="dropdown-value">
id should not provide

2024-05-30 07:25 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/componentreport/clientlibs/componentReport/js/componentReport.js
> +document.getElementById('button').addEventListener('click',function(){
load the js after content loaded

2024-05-30 07:25 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/servlets/ComponentReportServlet.java
> +
In this servlet at line no 43, is not the correct way to get logger

2024-05-30 10:39 UTC, abhinav-agarwal requested changes

2024-05-30 10:39 UTC, abhinav-agarwal commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/componentreport/clientlibs/componentReport/js/componentReport.js
> +     console.log(value);
please remove this console.log

2024-05-30 10:39 UTC, abhinav-agarwal commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/componentreport/clientlibs/componentReport/js/componentReport.js
> +          let apiUrl = "http://localhost:4502/content/aemtraining/Student/ss/jcr:content/root/container/componentreport.json?Path="+value;
pls don't provide host

2024-05-30 10:39 UTC, abhinav-agarwal commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/componentreport/clientlibs/componentReport/js/componentReport.js
> +          let apiUrl = "http://localhost:4502/content/aemtraining/Student/ss/jcr:content/root/container/componentreport.json?Path="+value;
why are we using hardcoded path

2024-05-30 10:39 UTC, abhinav-agarwal commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/componentreport/clientlibs/componentReport/js/componentReport.js
> +          console.log(success[i]);
remove console

2024-05-30 12:33 UTC, abhinav-agarwal requested changes

2024-05-30 12:33 UTC, abhinav-agarwal commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/componentreport/clientlibs/componentReport/js/componentReport.js
> +      let value = dropdown.value;
what if dropdown is null

2024-05-31 07:35 UTC, abhinav-agarwal approved these changes

2024-05-31 07:35 UTC, merged