Pull request : Home Page Banner Component
Shivamraghu1208/aem-training pull request #4
Opened 2024-06-03 12:52 UTC by Shivamraghu1208

2024-06-03 14:06 UTC, akashsen-aurx requested changes

2024-06-03 14:06 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/homepagebanner/homepagebanner.html
> +    <div class="con" data-sly-test="${isAuthored}">
Is this check necessary?

2024-06-03 14:06 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/homepagebanner/homepagebanner.html
> +        <div class="img">
Class name is same as tag name, there may be a chance of conflict in future. Please update class name

2024-06-03 14:06 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/homepagebanner/homepagebanner.html
> +    <div class="con" data-sly-test="${isAuthored}">
Please give meaningful class name

2024-06-03 14:06 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/homepagebanner/clientlibs/hompageclientlibs/.content.xml
> +    dependencies="aemtraining.jquery.clientlibs"/>
Do we need this unnecessary dependency

2024-06-03 14:09 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/homepagebanner/homepagebanner.html
> +            <h2>${obj.description}</h2>
Add context for HTML

2024-06-17 07:50 UTC, akashsen-aurx requested changes

2024-06-17 07:50 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/homepagebanner/homepagebanner.html
> +            <img src="${homePageBannerModel.fileReference}">
please provide image alternative text. It is important.

2024-06-17 07:50 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/models/HomePageBannerModel.java
> +           String path = this.currentPage.getPath();
Here, we can have better logic.

2024-06-17 07:50 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/models/HomePageBannerModel.java
> +        return this.buttonLinkTo;
Here, buttonLintTo can blank in some cases, so please tested out that case.

2024-06-17 07:50 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/homepagebanner/homepagebanner.html
> +            <a href=" ${homePageBannerModel.buttonLinkTo}.html" target="_blank">
If I provide google.com link then it will add .html, which is unacceptable.

2024-06-17 07:50 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/homepagebanner/homepagebanner.html
> +<div data-sly-test="${homePageBannerModel.isPublishMode}">
Remove this extra div

2024-06-17 07:50 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/homepagebanner/clientlibs/hompageclientlibs/.content.xml
> +    categories="HomePageLibs"
Where are you using this category

2024-06-17 07:56 UTC, abhinav-agarwal requested changes

2024-06-17 07:56 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/models/HomePageBannerModel.java
> +    private String buttonLabel;
Please add a default values for all the injected fields

2024-06-17 07:56 UTC, abhinav-agarwal commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/homepagebanner/homepagebanner.html
> +                <button>${homePageBannerModel.buttonLabel}</button>
What if buttonLabel is not authored.

2024-06-17 12:42 UTC, abhinav-agarwal approved these changes

2024-06-17 12:48 UTC, akashsen-aurx requested changes

2024-06-17 12:48 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/models/HomePageBannerModel.java
> +        if (title.isEmpty() || title == null) {
Is this (title == null) check is important?

2024-06-17 12:48 UTC, akashsen-aurx commented on ui.apps/src/main/content/jcr_root/apps/aemtraining/components/homepagebanner/homepagebanner.html
> +            <img alt="loading.. image" src="${homePageBannerModel.fileReference}">
close the img tag

2024-06-17 12:58 UTC, abhinav-agarwal requested changes

2024-06-17 12:58 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/models/HomePageBannerModel.java
> +        if (title.isEmpty()) {
what if space is authored in dialog?

2024-06-20 09:28 UTC, abhinav-agarwal approved these changes

2024-06-20 09:28 UTC, merged