Added page-unpublish-scheduler
Shivamraghu1208/aem-training pull request #7
Opened 2024-06-19 14:51 UTC by Shivamraghu1208

2024-06-20 06:01 UTC, akashsen-aurx requested changes

2024-06-20 06:01 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +                                e.printStackTrace();
Use logger for print exception.

2024-06-20 06:01 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +                                log.info("\n ==========================PATH OF PAGES WHERE EXPIRE CODE IS PRESENT =======================" + pageResource);
Don't use the equals symbol in the logger.

2024-06-20 06:01 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +
If this is unnecessary blank line then please remove it.

2024-06-20 06:01 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +    private List<String> buildAndExecuteQuery(JsonObject asJsonObject) {
asJsonObject name looks like a boolean variable name, please update it.

2024-06-20 06:01 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +    private List<String> buildAndExecuteQuery(JsonObject asJsonObject) {
If you are getting a list of pages then method name should be change, so please update the name.

2024-06-20 06:01 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +                    log.info("\n ==========================Code Present =======================" + code);
Write proper log, and use debug instead info.

2024-06-20 06:01 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +                                    repositoryException.printStackTrace();
Use logger

2024-06-20 06:01 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +        return null;
you can return listOfPageResource instead of null

2024-06-20 06:01 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +            params.put(ResourceResolverFactory.SUBSERVICE, "aem-training-content-reader");
Use String Constant instead of hard code value

2024-06-20 06:01 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +                log.error("Login Exception : {}",e);
provide full error message

2024-06-20 06:01 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +                e.printStackTrace();
use logger

2024-06-20 06:01 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +            String username = "admin";
use encrypted text

2024-06-20 06:01 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +        String apiUrl = "http://localhost:4502/bin/getCarCodes";
don't use hard code value

2024-06-20 06:01 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +        JsonObject asJsonObject = fetchApiResponse(apiUrl);
Give meaning full variable name

2024-06-20 06:01 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +            List<String> listOfPageResource = buildAndExecuteQuery(asJsonObject);
meaning full variable name

2024-06-20 06:01 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +        log.info("\n ==========================Run From Demo Method running=======================");
use debug and update logger message

2024-06-20 09:40 UTC, akashsen-aurx requested changes

2024-06-20 09:40 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +        log.debug("Scheduler Activated ");
Give scheduler name

2024-06-20 09:40 UTC, akashsen-aurx commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +        log.debug("\nRun From Demo Method running");
meaning full log

2024-06-20 10:23 UTC, abhinav-agarwal requested changes

2024-06-20 10:23 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +    private static final String ENCRYPTED_USER_NAME = "{bf369c8b28cee021f9f00e23b2ca9321bc279b60e408df065fc6a820d12f90f8}";
why have you taken this as string constant?

2024-06-20 10:23 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +    private static final String ENCRYPTED_USER_PASSWORD = "{bf369c8b28cee021f9f00e23b2ca9321bc279b60e408df065fc6a820d12f90f8}";
why have you taken this as string constant?

2024-06-20 10:23 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +        log.debug("Unpublished page Scheduler Activated ");
please pring api url with log

2024-06-20 10:23 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +        log.debug("Run Method Started");
please give a proper lg statement

2024-06-20 10:23 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
>          JsonObject jsonResponse = fetchApiResponse(apiUrl);
why to pass api url in parameter as it a global variable

2024-06-20 10:23 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +                    log.debug("PATH OF PAGES WHERE EXPIRE CODE IS PRESENT" + pageResource);
why this log statement is written in uppercase?

2024-06-20 10:23 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +                    log.debug("PATH OF PAGES WHERE EXPIRE CODE IS PRESENT" + pageResource);
please follow a proper logging syntax

2024-06-20 10:23 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
>                      log.error("ReplicationException {} {}", e, e.getMessage());
please follow a proper logging syntax

2024-06-20 10:23 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +                    log.debug("Code Present" + code);
please follow a proper logging syntax

2024-06-20 10:23 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +            e.printStackTrace();
please add a logger here

2024-06-20 10:26 UTC, abhinav-agarwal requested changes

2024-06-20 10:26 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +    CryptoSupport cryptoSupport;
mark this as private

2024-06-20 10:26 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +    protected Replicator replicator;
why protected here?

2024-06-20 10:26 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +        return resourceResolver.adaptTo(Session.class);
please don't write method for single liner code

2024-06-20 10:26 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +        if (resourceResolver != null) {
please close the resolver once your work is done

2024-06-20 10:26 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +            log.error("MalformedURLException {} {}", e, e.getMessage());
use proper logging syntax

2024-06-20 10:26 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +            log.error("IOException {} {}", e, e.getMessage());
use proper logging syntax

2024-06-20 10:26 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/services/config/PageUnpublishSchedulerConfiguration.java
> +    public String scheduler_name();
are we using this?

2024-06-20 10:26 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/services/config/PageUnpublishSchedulerConfiguration.java
> +    public String scheduler_expression();
are we using this?

2024-06-20 11:01 UTC, Shivamraghu1208 commented on core/src/main/java/com/adobe/aem/sample/site/core/services/config/PageUnpublishSchedulerConfiguration.java
> +    public String scheduler_expression();
yes

2024-06-20 11:12 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/services/config/PageUnpublishSchedulerConfiguration.java
> +    public String scheduler_expression();
okay

2024-06-21 12:40 UTC, abhinav-agarwal requested changes

2024-06-21 12:40 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +            JsonArray asJsonArray = jsonResponse.getAsJsonArray("responseCodes");
meaningful variable name

2024-06-21 12:40 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +            if (listOfPagePath != null) {
invald null check

2024-06-21 12:40 UTC, abhinav-agarwal commented on core/src/main/java/com/adobe/aem/sample/site/core/schedulers/PageUnpublishScheduler.java
> +            for (String pageResource : listOfPagePath) {
meaningfule variable name

2024-06-21 13:16 UTC, abhinav-agarwal approved these changes

2024-06-21 13:16 UTC, merged